### ISSUE TITLE
'anchor.borrow.getCollateralValue' occurs an error with a random address.

### ISSUE THREAD

**Issue by hsk-kr** [Anchor-Protocol/anchor.js#17]
Code
```typescript
const address = 'terra1fpnt5t2094g3amcwdv3akl60jg9uafgtc38px8';


const borrowedValue = await anchor.borrow.getBorrowedValue({
  market: MARKET_DENOMS.UUSD,
  address,
});

const borrowLimit = await anchor.borrow.getBorrowLimit({
  market: MARKET_DENOMS.UUSD,
  address,
});

console.log(borrowedValue);
console.log(borrowLimit);
```

Output
```
0.000000000000000000
0.000000000000000000
```

It works but

Code
```typescript
const address = 'terra1fpnt5t2094g3amcwdv3akl60jg9uafgtc38px8';

const collateralValue = await anchor.borrow.getCollateralValue({
  market: MARKET_DENOMS.UUSD,
  address,
});

console.log(collateralValue);
```

Output
```
TypeError: Cannot read property 'collateral' of null
    at C:\Users\HSK\programming\anchor-command-tools\node_modules\@anchor-protocol\anchor.js\src\facade\borrow\borrow.ts:95:39
    at Array.find (<anonymous>)
    at C:\Users\HSK\programming\anchor-command-tools\node_modules\@anchor-protocol\anchor.js\src\facade\borrow\borrow.ts:94:50
    at Array.reduce (<anonymous>)
    at Borrow.<anonymous> (C:\Users\HSK\programming\anchor-command-tools\node_modules\@anchor-protocol\anchor.js\src\facade\borrow\borrow.ts:93:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\HSK\programming\anchor-command-tools\node_modules\@anchor-protocol\anchor.js\dist\facade\borrow\borrow.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This code occurs an error.
I used a random address that were in my wallet history for test.
I changed the address to my wallet address. It worked well.

Are there addresses that can't get collateral value?

**Comment by kjessec** [comment]
@hsk-kr true, a random address which has no collateral wouldn't have any collateral listed, making code to fail. I'll make a patch so that it returns an empty collateral

**Comment by hsk-kr** [comment]
> @hsk-kr true, a random address which has no collateral wouldn't have any collateral listed, making code to fail. I'll make a patch so that it returns an empty collateral

Thank you for your answer.
I'll close this issue.
